sonar.projectKey=aause2gruppe5_skyjo_aau26_se2_backend
sonar.organization=aause2gruppe5
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.kotlin.file.suffixes=.kt,.kts
sonar.sourceEncoding=UTF-8
